[package]
name = "zkpassport_token"
authors = [""]
compiler_version = ">=0.16.0"
type = "contract"

[dependencies]
aztec =          { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.16.9", directory="yarn-project/aztec-nr/aztec" }
safe_math =      { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.16.9", directory="yarn-project/aztec-nr/safe-math" }
field_note =     { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.16.9", directory="yarn-project/aztec-nr/field-note" }
authwit =        { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.16.9", directory="yarn-project/aztec-nr/authwit" }
protocol_types = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.16.9", directory="yarn-project/noir-protocol-circuits/src/crates/types" }
